default:
  http_metas:
    content-type: text/html

  metas:
    title:        CMIS Administrator Backend
    robots:       CMIS Administrator Backend
    description:  CMIS Administrator Backend
    keywords:     CMIS Administrator Backend
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
