<?php
// auto-generated by sfPropelCrud
// date: 2013/03/12 13:31:26
?>
<h1>zMlmDistributor</h1>

<table>
<thead>
<tr>
  <th>Distributor</th>
  <th>Distributor code</th>
  <th>User</th>
  <th>Status code</th>
  <th>Full name</th>
  <th>Nickname</th>
  <th>Mt4 user name</th>
  <th>Mt4 password</th>
  <th>Ic</th>
  <th>Country</th>
  <th>Address</th>
  <th>Address2</th>
  <th>City</th>
  <th>State</th>
  <th>Postcode</th>
  <th>Email</th>
  <th>Alternate email</th>
  <th>Contact</th>
  <th>Gender</th>
  <th>Dob</th>
  <th>Bank name</th>
  <th>Bank acc no</th>
  <th>Bank holder name</th>
  <th>Bank swift code</th>
  <th>Visa debit card</th>
  <th>Ezy cash card</th>
  <th>Tree level</th>
  <th>Tree structure</th>
  <th>Placement tree level</th>
  <th>Placement tree structure</th>
  <th>Init rank</th>
  <th>Init rank code</th>
  <th>Upline dist</th>
  <th>Upline dist code</th>
  <th>Tree upline dist</th>
  <th>Tree upline dist code</th>
  <th>Total left</th>
  <th>Total right</th>
  <th>Placement position</th>
  <th>Placement datetime</th>
  <th>Rank</th>
  <th>Rank code</th>
  <th>Active datetime</th>
  <th>Activated by</th>
  <th>Leverage</th>
  <th>Spread</th>
  <th>Deposit currency</th>
  <th>Deposit amount</th>
  <th>Sign name</th>
  <th>Sign date</th>
  <th>Term condition</th>
  <th>Ib commission</th>
  <th>Is ib</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
  <th>Package purchase flag</th>
  <th>File bank pass book</th>
  <th>File proof of residence</th>
  <th>File nric</th>
  <th>Excluded structure</th>
  <th>Product mte</th>
  <th>Product fxgold</th>
  <th>Remark</th>
  <th>Loan account</th>
</tr>
</thead>
<tbody>
<?php foreach ($mlm_distributors as $mlm_distributor): ?>
<tr>
    <td><?php echo link_to($mlm_distributor->getDistributorId(), 'zMlmDistributor/show?distributor_id='.$mlm_distributor->getDistributorId()) ?></td>
      <td><?php echo $mlm_distributor->getDistributorCode() ?></td>
      <td><?php echo $mlm_distributor->getUserId() ?></td>
      <td><?php echo $mlm_distributor->getStatusCode() ?></td>
      <td><?php echo $mlm_distributor->getFullName() ?></td>
      <td><?php echo $mlm_distributor->getNickname() ?></td>
      <td><?php echo $mlm_distributor->getMt4UserName() ?></td>
      <td><?php echo $mlm_distributor->getMt4Password() ?></td>
      <td><?php echo $mlm_distributor->getIc() ?></td>
      <td><?php echo $mlm_distributor->getCountry() ?></td>
      <td><?php echo $mlm_distributor->getAddress() ?></td>
      <td><?php echo $mlm_distributor->getAddress2() ?></td>
      <td><?php echo $mlm_distributor->getCity() ?></td>
      <td><?php echo $mlm_distributor->getState() ?></td>
      <td><?php echo $mlm_distributor->getPostcode() ?></td>
      <td><?php echo $mlm_distributor->getEmail() ?></td>
      <td><?php echo $mlm_distributor->getAlternateEmail() ?></td>
      <td><?php echo $mlm_distributor->getContact() ?></td>
      <td><?php echo $mlm_distributor->getGender() ?></td>
      <td><?php echo $mlm_distributor->getDob() ?></td>
      <td><?php echo $mlm_distributor->getBankName() ?></td>
      <td><?php echo $mlm_distributor->getBankAccNo() ?></td>
      <td><?php echo $mlm_distributor->getBankHolderName() ?></td>
      <td><?php echo $mlm_distributor->getBankSwiftCode() ?></td>
      <td><?php echo $mlm_distributor->getVisaDebitCard() ?></td>
      <td><?php echo $mlm_distributor->getEzyCashCard() ?></td>
      <td><?php echo $mlm_distributor->getTreeLevel() ?></td>
      <td><?php echo $mlm_distributor->getTreeStructure() ?></td>
      <td><?php echo $mlm_distributor->getPlacementTreeLevel() ?></td>
      <td><?php echo $mlm_distributor->getPlacementTreeStructure() ?></td>
      <td><?php echo $mlm_distributor->getInitRankId() ?></td>
      <td><?php echo $mlm_distributor->getInitRankCode() ?></td>
      <td><?php echo $mlm_distributor->getUplineDistId() ?></td>
      <td><?php echo $mlm_distributor->getUplineDistCode() ?></td>
      <td><?php echo $mlm_distributor->getTreeUplineDistId() ?></td>
      <td><?php echo $mlm_distributor->getTreeUplineDistCode() ?></td>
      <td><?php echo $mlm_distributor->getTotalLeft() ?></td>
      <td><?php echo $mlm_distributor->getTotalRight() ?></td>
      <td><?php echo $mlm_distributor->getPlacementPosition() ?></td>
      <td><?php echo $mlm_distributor->getPlacementDatetime() ?></td>
      <td><?php echo $mlm_distributor->getRankId() ?></td>
      <td><?php echo $mlm_distributor->getRankCode() ?></td>
      <td><?php echo $mlm_distributor->getActiveDatetime() ?></td>
      <td><?php echo $mlm_distributor->getActivatedBy() ?></td>
      <td><?php echo $mlm_distributor->getLeverage() ?></td>
      <td><?php echo $mlm_distributor->getSpread() ?></td>
      <td><?php echo $mlm_distributor->getDepositCurrency() ?></td>
      <td><?php echo $mlm_distributor->getDepositAmount() ?></td>
      <td><?php echo $mlm_distributor->getSignName() ?></td>
      <td><?php echo $mlm_distributor->getSignDate() ?></td>
      <td><?php echo $mlm_distributor->getTermCondition() ?></td>
      <td><?php echo $mlm_distributor->getIbCommission() ?></td>
      <td><?php echo $mlm_distributor->getIsIb() ?></td>
      <td><?php echo $mlm_distributor->getCreatedBy() ?></td>
      <td><?php echo $mlm_distributor->getCreatedOn() ?></td>
      <td><?php echo $mlm_distributor->getUpdatedBy() ?></td>
      <td><?php echo $mlm_distributor->getUpdatedOn() ?></td>
      <td><?php echo $mlm_distributor->getPackagePurchaseFlag() ?></td>
      <td><?php echo $mlm_distributor->getFileBankPassBook() ?></td>
      <td><?php echo $mlm_distributor->getFileProofOfResidence() ?></td>
      <td><?php echo $mlm_distributor->getFileNric() ?></td>
      <td><?php echo $mlm_distributor->getExcludedStructure() ?></td>
      <td><?php echo $mlm_distributor->getProductMte() ?></td>
      <td><?php echo $mlm_distributor->getProductFxgold() ?></td>
      <td><?php echo $mlm_distributor->getRemark() ?></td>
      <td><?php echo $mlm_distributor->getLoanAccount() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zMlmDistributor/create') ?>
