<?php
// auto-generated by sfPropelCrud
// date: 2013/03/12 13:31:26
?>
<table>
<tbody>
<tr>
<th>Distributor: </th>
<td><?php echo $mlm_distributor->getDistributorId() ?></td>
</tr>
<tr>
<th>Distributor code: </th>
<td><?php echo $mlm_distributor->getDistributorCode() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $mlm_distributor->getUserId() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_distributor->getStatusCode() ?></td>
</tr>
<tr>
<th>Full name: </th>
<td><?php echo $mlm_distributor->getFullName() ?></td>
</tr>
<tr>
<th>Nickname: </th>
<td><?php echo $mlm_distributor->getNickname() ?></td>
</tr>
<tr>
<th>Mt4 user name: </th>
<td><?php echo $mlm_distributor->getMt4UserName() ?></td>
</tr>
<tr>
<th>Mt4 password: </th>
<td><?php echo $mlm_distributor->getMt4Password() ?></td>
</tr>
<tr>
<th>Ic: </th>
<td><?php echo $mlm_distributor->getIc() ?></td>
</tr>
<tr>
<th>Country: </th>
<td><?php echo $mlm_distributor->getCountry() ?></td>
</tr>
<tr>
<th>Address: </th>
<td><?php echo $mlm_distributor->getAddress() ?></td>
</tr>
<tr>
<th>Address2: </th>
<td><?php echo $mlm_distributor->getAddress2() ?></td>
</tr>
<tr>
<th>City: </th>
<td><?php echo $mlm_distributor->getCity() ?></td>
</tr>
<tr>
<th>State: </th>
<td><?php echo $mlm_distributor->getState() ?></td>
</tr>
<tr>
<th>Postcode: </th>
<td><?php echo $mlm_distributor->getPostcode() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $mlm_distributor->getEmail() ?></td>
</tr>
<tr>
<th>Alternate email: </th>
<td><?php echo $mlm_distributor->getAlternateEmail() ?></td>
</tr>
<tr>
<th>Contact: </th>
<td><?php echo $mlm_distributor->getContact() ?></td>
</tr>
<tr>
<th>Gender: </th>
<td><?php echo $mlm_distributor->getGender() ?></td>
</tr>
<tr>
<th>Dob: </th>
<td><?php echo $mlm_distributor->getDob() ?></td>
</tr>
<tr>
<th>Bank name: </th>
<td><?php echo $mlm_distributor->getBankName() ?></td>
</tr>
<tr>
<th>Bank acc no: </th>
<td><?php echo $mlm_distributor->getBankAccNo() ?></td>
</tr>
<tr>
<th>Bank holder name: </th>
<td><?php echo $mlm_distributor->getBankHolderName() ?></td>
</tr>
<tr>
<th>Bank swift code: </th>
<td><?php echo $mlm_distributor->getBankSwiftCode() ?></td>
</tr>
<tr>
<th>Visa debit card: </th>
<td><?php echo $mlm_distributor->getVisaDebitCard() ?></td>
</tr>
<tr>
<th>Ezy cash card: </th>
<td><?php echo $mlm_distributor->getEzyCashCard() ?></td>
</tr>
<tr>
<th>Tree level: </th>
<td><?php echo $mlm_distributor->getTreeLevel() ?></td>
</tr>
<tr>
<th>Tree structure: </th>
<td><?php echo $mlm_distributor->getTreeStructure() ?></td>
</tr>
<tr>
<th>Placement tree level: </th>
<td><?php echo $mlm_distributor->getPlacementTreeLevel() ?></td>
</tr>
<tr>
<th>Placement tree structure: </th>
<td><?php echo $mlm_distributor->getPlacementTreeStructure() ?></td>
</tr>
<tr>
<th>Init rank: </th>
<td><?php echo $mlm_distributor->getInitRankId() ?></td>
</tr>
<tr>
<th>Init rank code: </th>
<td><?php echo $mlm_distributor->getInitRankCode() ?></td>
</tr>
<tr>
<th>Upline dist: </th>
<td><?php echo $mlm_distributor->getUplineDistId() ?></td>
</tr>
<tr>
<th>Upline dist code: </th>
<td><?php echo $mlm_distributor->getUplineDistCode() ?></td>
</tr>
<tr>
<th>Tree upline dist: </th>
<td><?php echo $mlm_distributor->getTreeUplineDistId() ?></td>
</tr>
<tr>
<th>Tree upline dist code: </th>
<td><?php echo $mlm_distributor->getTreeUplineDistCode() ?></td>
</tr>
<tr>
<th>Total left: </th>
<td><?php echo $mlm_distributor->getTotalLeft() ?></td>
</tr>
<tr>
<th>Total right: </th>
<td><?php echo $mlm_distributor->getTotalRight() ?></td>
</tr>
<tr>
<th>Placement position: </th>
<td><?php echo $mlm_distributor->getPlacementPosition() ?></td>
</tr>
<tr>
<th>Placement datetime: </th>
<td><?php echo $mlm_distributor->getPlacementDatetime() ?></td>
</tr>
<tr>
<th>Rank: </th>
<td><?php echo $mlm_distributor->getRankId() ?></td>
</tr>
<tr>
<th>Rank code: </th>
<td><?php echo $mlm_distributor->getRankCode() ?></td>
</tr>
<tr>
<th>Active datetime: </th>
<td><?php echo $mlm_distributor->getActiveDatetime() ?></td>
</tr>
<tr>
<th>Activated by: </th>
<td><?php echo $mlm_distributor->getActivatedBy() ?></td>
</tr>
<tr>
<th>Leverage: </th>
<td><?php echo $mlm_distributor->getLeverage() ?></td>
</tr>
<tr>
<th>Spread: </th>
<td><?php echo $mlm_distributor->getSpread() ?></td>
</tr>
<tr>
<th>Deposit currency: </th>
<td><?php echo $mlm_distributor->getDepositCurrency() ?></td>
</tr>
<tr>
<th>Deposit amount: </th>
<td><?php echo $mlm_distributor->getDepositAmount() ?></td>
</tr>
<tr>
<th>Sign name: </th>
<td><?php echo $mlm_distributor->getSignName() ?></td>
</tr>
<tr>
<th>Sign date: </th>
<td><?php echo $mlm_distributor->getSignDate() ?></td>
</tr>
<tr>
<th>Term condition: </th>
<td><?php echo $mlm_distributor->getTermCondition() ?></td>
</tr>
<tr>
<th>Ib commission: </th>
<td><?php echo $mlm_distributor->getIbCommission() ?></td>
</tr>
<tr>
<th>Is ib: </th>
<td><?php echo $mlm_distributor->getIsIb() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_distributor->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_distributor->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_distributor->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_distributor->getUpdatedOn() ?></td>
</tr>
<tr>
<th>Package purchase flag: </th>
<td><?php echo $mlm_distributor->getPackagePurchaseFlag() ?></td>
</tr>
<tr>
<th>File bank pass book: </th>
<td><?php echo $mlm_distributor->getFileBankPassBook() ?></td>
</tr>
<tr>
<th>File proof of residence: </th>
<td><?php echo $mlm_distributor->getFileProofOfResidence() ?></td>
</tr>
<tr>
<th>File nric: </th>
<td><?php echo $mlm_distributor->getFileNric() ?></td>
</tr>
<tr>
<th>Excluded structure: </th>
<td><?php echo $mlm_distributor->getExcludedStructure() ?></td>
</tr>
<tr>
<th>Product mte: </th>
<td><?php echo $mlm_distributor->getProductMte() ?></td>
</tr>
<tr>
<th>Product fxgold: </th>
<td><?php echo $mlm_distributor->getProductFxgold() ?></td>
</tr>
<tr>
<th>Remark: </th>
<td><?php echo $mlm_distributor->getRemark() ?></td>
</tr>
<tr>
<th>Loan account: </th>
<td><?php echo $mlm_distributor->getLoanAccount() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmDistributor/edit?distributor_id='.$mlm_distributor->getDistributorId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmDistributor/list') ?>
