<?php
// auto-generated by sfPropelCrud
// date: 2013/07/18 11:33:15
?>
<h1>zMlmArticle</h1>

<table>
<thead>
<tr>
  <th>Article</th>
  <th>Article title</th>
  <th>Article type</th>
  <th>Article category</th>
  <th>Article content</th>
  <th>Read qty</th>
  <th>Publiser name</th>
  <th>Status code</th>
  <th>Created by</th>
  <th>Created on</th>
  <th>Updated by</th>
  <th>Updated on</th>
</tr>
</thead>
<tbody>
<?php foreach ($mlm_articles as $mlm_article): ?>
<tr>
    <td><?php echo link_to($mlm_article->getArticleId(), 'zMlmArticle/show?article_id='.$mlm_article->getArticleId()) ?></td>
      <td><?php echo $mlm_article->getArticleTitle() ?></td>
      <td><?php echo $mlm_article->getArticleType() ?></td>
      <td><?php echo $mlm_article->getArticleCategory() ?></td>
      <td><?php echo $mlm_article->getArticleContent() ?></td>
      <td><?php echo $mlm_article->getReadQty() ?></td>
      <td><?php echo $mlm_article->getPubliserName() ?></td>
      <td><?php echo $mlm_article->getStatusCode() ?></td>
      <td><?php echo $mlm_article->getCreatedBy() ?></td>
      <td><?php echo $mlm_article->getCreatedOn() ?></td>
      <td><?php echo $mlm_article->getUpdatedBy() ?></td>
      <td><?php echo $mlm_article->getUpdatedOn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'zMlmArticle/create') ?>
