<?php
// auto-generated by sfPropelCrud
// date: 2013/07/18 11:33:15
?>
<table>
<tbody>
<tr>
<th>Article: </th>
<td><?php echo $mlm_article->getArticleId() ?></td>
</tr>
<tr>
<th>Article title: </th>
<td><?php echo $mlm_article->getArticleTitle() ?></td>
</tr>
<tr>
<th>Article type: </th>
<td><?php echo $mlm_article->getArticleType() ?></td>
</tr>
<tr>
<th>Article category: </th>
<td><?php echo $mlm_article->getArticleCategory() ?></td>
</tr>
<tr>
<th>Article content: </th>
<td><?php echo $mlm_article->getArticleContent() ?></td>
</tr>
<tr>
<th>Read qty: </th>
<td><?php echo $mlm_article->getReadQty() ?></td>
</tr>
<tr>
<th>Publiser name: </th>
<td><?php echo $mlm_article->getPubliserName() ?></td>
</tr>
<tr>
<th>Status code: </th>
<td><?php echo $mlm_article->getStatusCode() ?></td>
</tr>
<tr>
<th>Created by: </th>
<td><?php echo $mlm_article->getCreatedBy() ?></td>
</tr>
<tr>
<th>Created on: </th>
<td><?php echo $mlm_article->getCreatedOn() ?></td>
</tr>
<tr>
<th>Updated by: </th>
<td><?php echo $mlm_article->getUpdatedBy() ?></td>
</tr>
<tr>
<th>Updated on: </th>
<td><?php echo $mlm_article->getUpdatedOn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'zMlmArticle/edit?article_id='.$mlm_article->getArticleId()) ?>
&nbsp;<?php echo link_to('list', 'zMlmArticle/list') ?>
