<?php
// auto-generated by sfPropelCrud
// date: 2013/07/18 11:33:15
?>
<?php use_helper('Object') ?>

<?php echo form_tag('zMlmArticle/update') ?>

<?php echo object_input_hidden_tag($mlm_article, 'getArticleId') ?>

<table>
<tbody>
<tr>
  <th>Article title*:</th>
  <td><?php echo object_textarea_tag($mlm_article, 'getArticleTitle', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Article type*:</th>
  <td><?php echo object_input_tag($mlm_article, 'getArticleType', array (
  'size' => 25,
  'value' => 'LEARN',
)) ?></td>
</tr>
<tr>
  <th>Article category*:</th>
  <td><?php echo object_textarea_tag($mlm_article, 'getArticleCategory', array (
  'size' => '30x3',
  'value' => '学习园地',
)) ?></td>
</tr>
<tr>
  <th>Article content*:</th>
  <td><?php echo object_textarea_tag($mlm_article, 'getArticleContent', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Read qty*:</th>
  <td><?php echo object_input_tag($mlm_article, 'getReadQty', array (
  'size' => 7,
  'value' => 188,
)) ?></td>
</tr>
<tr>
  <th>Publiser name*:</th>
  <td><?php echo object_input_tag($mlm_article, 'getPubliserName', array (
  'size' => 80,
  'value' => '公司管理员',
)) ?></td>
</tr>
<tr>
  <th>Status code*:</th>
  <td><?php echo object_input_tag($mlm_article, 'getStatusCode', array (
  'size' => 20,
  'value' => 'ACTIVE',
)) ?></td>
</tr>
<tr>
  <th>Created by*:</th>
  <td><?php echo object_input_tag($mlm_article, 'getCreatedBy', array (
  'size' => 7,
  'value' => 1,
)) ?></td>
</tr>
<tr>
  <th>Updated by*:</th>
  <td><?php echo object_input_tag($mlm_article, 'getUpdatedBy', array (
  'size' => 7,
  'value' => 1,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($mlm_article->getArticleId()): ?>
  &nbsp;<?php echo link_to('delete', 'zMlmArticle/delete?article_id='.$mlm_article->getArticleId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmArticle/show?article_id='.$mlm_article->getArticleId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'zMlmArticle/list') ?>
<?php endif; ?>
</form>
