default:
  http_metas:
    content-type: text/html

  metas:
    title:        FX-CMISC
    robots:       FX-CMISC
    description:  FX-CMISC
    keywords:     FX-CMISC
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
